sudo: required
services:
- docker

language: node_js
node_js:
  - "8"

before_install:
  - pip install --upgrade --user awscli
  - cd lambda

install: yarn

script: yarn test

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bin/lambda-deploy.sh; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bin/docker-build-and-deploy.sh; fi
